apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghme-back-end
  namespace: kimia-zahra-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: loghme-back-end
  template:
    metadata:
      labels:
        app: loghme-back-end
    spec:
      containers:
        - image: index.docker.io/zahramo99/loghme:backend
          imagePullPolicy: Always
          name: loghme-back-end
          ports:
            - containerPort: 8080
          resources:
              limits:
                memory: "250Mi"
                cpu: "250m"
              requests:
                memory: "250Mi"
                cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: loghme-back-end
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32002
  selector:
    app: loghme-back-end